d_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main_page.views import about, contacts, classes, join_us, schedule
from account.views import registration_view, login_view, logout_view


urlpatterns = [
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('classes/', classes, name='classes'),
    path('join_us/', join_us, name='join_us'),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('registration/', registration_view, name='registration_view'),
    path('schedule/', schedule, name='schedule'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path
from main_page.views import index, update_manager, manager_list

app_name = 'main_page'



urlpatterns = [
    path('', index, name='index'),
    path('manager/update_manager/<int:pk>', update_manager, name='update_manager'),
    path('manager/manager_list/', manager_list, name='manager_list'),
    ]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
"""
This module contains two Django form classes: UserLogin and UserRegistration.

UserLogin is a form for authenticating user login credentials. It takes a username and password input from the user,
verifies that the username and password are valid, and raises a ValidationError if they are not.

UserRegistration is a form for creating new user accounts. It takes a username, password, and password confirmation
input from the user, verifies that the passwords match, and raises a ValidationError if they do not.

Inputs:
- UserLogin form: username (str), password (str)
- UserRegistration form: username (str), password (str), password2 (str)
"""


from django import forms
from django.contrib.auth import get_user_model, authenticate


User = get_user_model()

class UserLogin(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user or not user.check_password(password):
                raise forms.ValidationError('Error in Login or Password')
        else:
            raise forms.ValidationError('Error in Login or Password')
        return super().clean()


class UserRegistration(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username',)

    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data['password2']
        raise forms.ValidationError('Error in password!')

account/views.py
"""
This module contains views for user registration and login pages.

Functions:
- logout_view: Logs out the current user and redirects to the homepage.
- login_view: Renders the login form and handles user authentication.
- registration_view: Renders the registration form and creates a new user.

Dependencies:
- render: Renders an HTML template with a given context dictionary.
- redirect: Redirects to a given URL.
- get_common_context: A function from the main_page.context_data module that returns a dictionary with common
context data for all pages.
- UserRegistration: A Django form class for user registration.
- UserLogin: A Django form class for user login.
- authenticate: Authenticates a user with a given username and password.
- login: Logs in a user and creates a session.
- logout: Logs out the current user and destroys the session.
- User: The Django user model for the application.

"""

from django.shortcuts import render, redirect
from main_page.context_data import get_common_context
from .forms import UserRegistration, UserLogin
from django.contrib.auth import login, authenticate, logout


def logout_view(request):
    logout(request)
    return redirect('/')

def login_view(request):
    form = UserLogin(request.POST or None)
    next_get = request.GET.get('next')
    user_manager = request.user.groups.filter(name='manager').exists()
    user_auth = request.user.is_authenticated

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)

        next_post = request.POST.get('next')
        return redirect(next_get or next_post or '/')

    data = {
        'form': form,
        'user_manager': user_manager,
        'user_auth': user_auth,
    }
    context_data = get_common_context()
    data.update(context_data)
    return render(request, 'login.html', context=data)

def registration_view(request):
    form = UserRegistration(request.POST or None)
    user_manager = request.user.groups.filter(name='manager').exists()
    user_auth = request.user.is_authenticated
    context_data = get_common_context()

    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        data = {
            'form': form,
            'user_manager': user_manager,
            'user_auth': user_auth,
            'user': new_user,
        }
        data.update(context_data)
        return render(request, 'registration_done.html', context=data)

    data = {
        'form': form,
        'user_manager': user_manager,
        'user_auth': user_auth,
    }
    data.update(context_data)
    return render(request, 'registration.html', context=data)

account/templates/login.html
{% extends 'main.html' %}
{% load static %}
{% block title %}<title>Kider - Login </title>{% endblock %}


{% block content %}


<link rel="stylesheet" href="{% static "css/sing.css" %}" media="screen" type="text/css" />

<div id="login-box">
  <div class="left">
    <h1>Login</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
            <button type="submit" name="signup_submit" value="Log in">Log in</button>
        </form>
  </div>

</div>

{% endblock %}

account/templates/manager.html
{% extends 'main.html' %}

{% block content %}
        <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
            <h3>Зворотній зв'язок</h3>
                {% for item in contact_us_viev_manager %}

                    <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'main_page:update_manager' pk=item.pk %}">
                            <button type="button" class="btn btn-primary">Закрити заявку</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.name }}</div>
                    <div class="col-md-3">{{ item.subject }}</div>
                    <div class="col-md-3">{{ item.email }}</div>
                    <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                </div>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-9"><p>{{ item.message }}</p></div>
                </div>
            {% endfor %}

                        <h3>Підписка на email розсилку</h3>
                {% for item in subscription_viev_manager %}
                    <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'main_page:update_manager' pk=item.pk %}">
                            <button type="button" class="btn btn-primary">Закрити заявку</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.email }}</div>
                    <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
            {% endfor %}

                <h3>Призначити зустріч</h3>
                {% for item in make_appointment_viev_manager %}

                    <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'main_page:update_manager' pk=item.pk %}">
                            <button type="button" class="btn btn-primary">Закрити заявку</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.name }}</div>
                    <div class="col-md-3">{{ item.email }}</div>
                    <div class="col-md-3">{{ item.child_name }}</div>
                    <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                </div>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-9"><p>{{ item.message }}</p></div>
                </div>
            {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

account/templates/registration.html
{% extends 'main.html' %}
{% load static %}
{% block title %}<title>Kider - Registration </title>{% endblock %}


{% block content %}


<link rel="stylesheet" href="{% static "css/sing.css" %}" media="screen" type="text/css" />

<div id="login-box">
  <div class="left">
    <h1>Sign up</h1>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
            <button type="submit" name="signup_submit" value="Sign me up">Sign me up</button>
        </form>
  </div>

</div>

{% endblock %}

account/templates/registration_done.html
{% extends 'main.html' %}

{% block content %}
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="display-4">Hello, {{ user.username }}</h1>
                    <p>You are successfully registered in the system!</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}