d_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main_page.views import about, contacts, classes, join_us, schedule
from account.views import registration_view, login_view, logout_view


urlpatterns = [
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('classes/', classes, name='classes'),
    path('join_us/', join_us, name='join_us'),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('registration/', registration_view, name='registration_view'),
    path('schedule/', schedule, name='schedule'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path
from main_page.views import index, update_manager, manager_list

app_name = 'main_page'



urlpatterns = [
    path('', index, name='index'),
    path('manager/update_manager/<int:pk>', update_manager, name='update_manager'),
    path('manager/manager_list/', manager_list, name='manager_list'),
    ]

templates/index.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

{% include 'slider.html' %}

{% include 'facilities.html' %}

{% include 'about_block.html' %}

{% include 'call.html' %}

{% include 'classes_block.html' %}

{% include 'appointment.html' %}

{% include 'team.html' %}

{% include 'testimonial.html' %}

{% endblock %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    {% block title %}<title>Kider - Preschool Website</title>{% endblock %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href='{% static "img/favicon.ico" %}' rel="icon">

    <!-- Google Web Fonts -->

    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href='{% static "css/all.min.css" %}' rel="stylesheet">
    <link href='{% static "css/bootstrap-icons.css" %}' rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href='{% static "lib/animate/animate.min.css" %}' rel="stylesheet">
    <link href='{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}' rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href='{% static "css/style.css" %}' rel="stylesheet">


</head>

<body>
     <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
         <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
            <a href="{% url 'main_page:index' %}" class="navbar-brand">
                <h1 class="m-0 text-primary"><i class="fa fa-book-reader me-3"></i>Kider</h1>
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="{% url 'main_page:index' %}" class="nav-item nav-link{% if request.path == '/' %} active{% endif %}">Home</a>
                    <a href="{% url 'about' %}" class="nav-item nav-link{% if request.path == '/about/' %} active{% endif %}">About Us</a>
                    <a href="{% url 'classes' %}" class="nav-item nav-link{% if request.path == '/classes/' %} active{% endif %}">Classes</a>
                    <a href="{% url 'contacts' %}" class="nav-item nav-link{% if request.path == '/contacts/' %} active{% endif %}">Contact Us</a>
                    {% if user_auth %}
                        <a href="{% url 'schedule' %}" class="nav-item nav-link{% if request.path == '/schedule/' %} active{% endif %}">Schedule</a>
                    {% endif %}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle{% if '/Account/' in request.path %} active{% endif %}" data-bs-toggle="dropdown">Account</a>
                        <div class="dropdown-menu rounded-0 rounded-bottom border-0 shadow-sm m-0">
                            <ul>
                                {% if not user_auth %}
                                    <li><a href={% url 'login_view' %}>Log in</a></li>
                                    <li><a href={% url 'registration_view' %}>Registration</a></li>
                                {% else %}
                                    <li><a href={% url 'logout_view' %}>Log out</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    {% if user_manager %}
                        <a href="{% url 'main_page:manager_list' %}" class="nav-item nav-link{% if request.path == '/manager/manager_list/' %} active{% endif %}">Managers work list</a>
                    {% endif %}

                </div>

                <a href="{% url 'join_us' %}" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Join Us<i class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        <!-- Navbar End -->
        {% block content %}

        {% endblock %}


        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h3 class="text-white mb-4">{{ contacts.h1 }}</h3>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>{{ contacts.address }}</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>{{ contacts.phone }}</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>{{ contacts.email }}</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href={{ contacts.twi_url }}><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href={{ contacts.fb_url }}><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href={{ contacts.youtube_url }}><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href={{ contacts.in_url }}><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h3 class="text-white mb-4">Quick Links</h3>
                        <a class="btn btn-link text-white-50" href="{% url 'about' %}">About Us</a>
                        <a class="btn btn-link text-white-50" href="{% url 'contacts' %}">Contact Us</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h3 class="text-white mb-4">Photo Gallery</h3>
                        <div class="row g-2 pt-2">
                            {% for item in gallery %}
                                <div class="col-4">
                                <img class="img-fluid rounded bg-light p-1" src="{{ item.image.url }}" onerror="this.onerror=null;this.src='{% static 'img/classes-4.jpg' %}';" alt="{{ item.name }}">
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h3 class="text-white mb-4">Newsletter</h3>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                            <form method="post">
                                {% csrf_token %}
                                <div class="position-relative mx-auto" style="max-width: 400px;">
                                {{ subscription.email }}
                                <button type="submit" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Kider</a>, All Right Reserved.

							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                            <br>Distributed By: <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                            <br>Backend developer: <a class="border-bottom" href="https://github.com/shamansk1y" target="_blank">shamansk1y</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src='{% static "js/jquery-3.4.1.min.js" %}'></script>
    <script src='{% static "js/bootstrap.bundle.min.js" %}'></script>
    <script src='{% static "lib/wow/wow.min.js" %}'></script>
    <script src='{% static "lib/easing/easing.min.js" %}'></script>
    <script src='{% static "lib/waypoints/waypoints.min.js" %}'></script>
    <script src='{% static "lib/owlcarousel/owl.carousel.min.js" %}'></script>

    <!-- Template Javascript -->
    <script src='{% static "js/main.js" %}'></script>
</body>

</html>